# Generated by Django 3.2.7 on 2021-09-21 04:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pieces',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('3dce48ea-42b6-47cd-bda7-f8fb8247c993'), editable=False, primary_key=True, serialize=False)),
                ('piece_name', models.CharField(max_length=255)),
                ('initial_position', models.CharField(max_length=3)),
                ('current_position', models.CharField(max_length=3)),
                ('previous_position', models.CharField(max_length=3)),
                ('next_positions', models.CharField(max_length=255)),
                ('nice_play', models.BooleanField(default=False)),
            ],
        ),
    ]
