# Generated by Django 3.2.7 on 2021-09-21 04:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pieces', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pieces',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9fab8f54-809e-4997-8759-a7ae5ad04553'), editable=False, primary_key=True, serialize=False),
        ),
    ]
