# Generated by Django 3.2.7 on 2021-09-21 05:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pieces', '0002_alter_pieces_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pieces',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e4471cd3-1083-4c85-8c09-caea1ad81ac0'), editable=False, primary_key=True, serialize=False),
        ),
    ]
